gh-md-toc, tests/tests.bats
simple addition : print usage also if no arguments given, not only if ```--help``` is given
this was the content of my previous pull request, that i just closed to create the current one, when i add a new test to check that we have the same output in this case than if ```--help``` was given.
By the way; some tests unrelated to this were already failing
```
panty@desk:[~/Documents/dev/github-markdown-toc]: bats tests
✓ TOC for local README.md
✗ TOC for remote README.md
(from function `assert_equal' in file tests/test_helper.bash, line 7,
in test file tests/tests.bats, line 32)
`assert_equal "${lines[2]}"  "  * [sitemap.js](#sitemapjs)"' failed
expected:   * [sitemap.js](op="mainContentOfPage"><h1><)
actual:     * [sitemap.js](#sitemapjs)
✗ TOC for mixed README.md (remote/local)
(from …
```
=> Help if no args given

gh-md-toc
decode the urlencoded characters to make the link readable. fix to Issue #6 .
=> decode urlencoded characters to make the link looks better

gh-md-toc
=> fix mktemp error on Mac OS X without coreutils.

gh-md-toc
It's an unimportant change, I know.
But the old code is reimplementing the behavior of the `case` builtin.
=> Use case builtin for pattern matching

gh-md-toc
Not sure if this is the best approach but without the token, requests fail pretty often with a "API rate limit exceeded" error. In that case the script fails to produce any TOC but also fails to report the error.
=> add optional GitHub API token

gh-md-toc
Similar to issues #22 and #24, I ran into some issues while attempting to run this in a modern-ish Linux environment (tested on both Ubuntu 16.04 LTS and CentOS 7.4).  It appears that the issue was with `sed`'s syntax:
```
sed: can't read .orig.2018-02-28_122230: No such file or directory
sed: can't read : No such file or directory
```
I was able to fix this by changing the syntax of `sed` and removing some character escapes.  The included tests successfully pass with this change:
```
$ make test
✓ TOC for local README.md
✓ TOC for remote README.md
✓ TOC for mixed README.md (remote/local)
✓ TOC for markdown from stdin
✓ --help
✓ no arguments
✓ --version
✓ TOC for non-english chars, #6, #10
✓ TOC for text with backquote, #13
9 tests, 0 failures
```
My environment:
```
$ uname -a
Linux …
```
=> Fix sed syntax for Linux

gh-md-toc
I locally renamed the file to `mdtoc` and now the help output doesn't match the actual executable name. This fixes the help output by using the name of the executed file instead of the hard-coded value.
=> Replace hard coded $app_name

gh-md-toc
- github api rate limited exceeded error is now reported and not silently failing
- plus suggests where to put github auth token
it's not the most elegant solution but it works.
thanks for the script.
=> fix silent github api rate limited exceeded problem

gh-md-toc
The check for GH_TOC_TOKEN was using the empty variable when it is
empty, instead of using the default. This change reverses the boolean
test to fix it.
Signed-off-by: Doug Hellmann <dhellmann@redhat.com>
=> reverse the logic for handling GH_TOC_TOKEN to correct it

Dockerfile, README.md
I added a simple Dockerfile to run your project from Docker
You can try it out directly by pulling from DockerHub:
```shell
docker run -it vemonet/markdown-toc-generator https://github.com/ekalinin/envirius/blob/master/README.md
```
=> Add Dockerfile to run it from Docker

README.md
This adds installation instructions using [Basher](https://github.com/basherpm/basher). For those who have it installed, this makes it faster to install shell scripts from Git repositories. The directory structure is directly compatble with Basher, so it didn't have to be modified.
This also replaces instances of OS X with macOS (which is the official name as of macOS 10.12).
=> Add installation instructions using Basher

gh-md-toc
Sometimes you can run gh-md-toc without markers in your file and it runs successfully. This will error.
=> Check if README.md has actual markers

gh-md-toc
This corrects "**basename: extra operand ‘VAL1’**" errors as seen below.
Also this moves the basename call to only occur when the help text is displayed.
> $ '/cygdrive/c/Users/myusername/OneDrive - VAL1 VAL2/Utils/github-markdown-toc/gh-md-toc' --help
> /cygdrive/c/Users/myusername/OneDrive - VAL1 VAL2/Utils/github-markdown-toc/gh-md-toc
> **basename: extra operand ‘VAL1’**
> Try 'basename --help' for more information.
> GitHub TOC generator (): 0.5.0
> 
> Usage:
>    [`--`insert] src [src]  Create TOC for a README file (url or local path)
>    `-`                     Create TOC for markdown from STDIN
>    `--`help                Show help
>    `--`version             Show version
=>  Correct BaseName Handling for Spaces in Path

gh-md-toc, tests/tests.bats
First time doing this, hopefully, you consider it for merging.
I tried to do a sed append, however, OSX sed requires a new line. It got really tricky and I abandoned it in favor of just generating the TOC files and deleting them. Dirty but works and keeps your repository clean of backup files.
=> Added Create TOC without backup option --ins-nb

gh-md-toc
Changed code to work on z/OS Unix System Services, and eliminated non-EBCDIC friendly characters from source.  Resolves Issue #98.
=> Add z/OS support to gh-md-toc

gh-md-toc, tests/test_plussign.md, tests/tests.bats
See: https://github.com/ekalinin/github-markdown-toc/issues/100
«
Plus signs in the toc's link texts (e.g: in "C++") are overzealously
converted to whitespaces #100
»
=> Fix for issue#100 ("+"s in titles)

gh-md-toc
When using the `--insert` option to write the TOC back to the analyzed file **without** using the `--no-backup` option, there is a bug because the `no_backup` variable is not set in the environment.
Example:
```
$ gh-md-toc --insert some_file.md 
Table of Contents
=================
* [generated toc cut off in this example](#generated-toc-cut-off-in-this-example)
Found markers
/home/user/bin/gh-md-toc: line 180: [: =: unary operator expected
!! TOC was added into: 'some_file.md'
!! Origin version of the file: 'some_file.md.orig.2021-01-30_142030'
!! TOC added into a separate file: 'some_file.md.toc.2021-01-30_142030'
```
As you can see above, there is an error message about a unary operator expected on line [line 180](https://github.com/ekalinin/github-markdown-toc/blob/171661836b949aca6c78 …
=> Bug when using `--insert` without `--no-backup`

gh-md-toc
Fixes #77
The bug was introduced in #104
You will find a test file here: https://github.com/zeitounator/random-files/blob/main/gh-markdown-toc-%23109-test-file.md#do-you-like-c
**Important note**: the bug was only present when generating the toc from a local file so you will have to save the raw content to a local `.md` file prior to testing. Here is the raw content from the url for reference. I kept the url to make sure there are no drawbacks when calling it directly.
```yaml
```
From what I can see:
* Title text retains the `+` when present as fixed in #104 
* urls for titles with special chars are again generated correctly
* generating directly from url is still ok after this fix
Generating from file before the fix:
```yaml
Table of Contents
=================
* [Test file for <a …
```
=> utf8 toc generation bug

gh-md-toc
Fixes https://github.com/ekalinin/github-markdown-toc/issues/111
This adds a `--hide-footer` flag to be used with `--insert`/`--no-backup`
=> Add --hide-footer flag

gh-md-toc
At the moment the TOC starts with an indentation : 
```
* [QuickStart](#quickstart)
* [Requirements](#requirements)
* [Setup](#setup)
```
It confuses other tools such as `mkdocs`.
This PR proposes to align the first level of bullets to the left.
=> Fix the indentation of the generated TOC

gh-md-toc
The original sed variant detection worked by checking the operating system type- if the OS is darwin (ie, OSX) it uses the BSD sed, otherwise the GNU sed.
This change instead uses "duck typing" to identify the variant. It runs `sed --version` to detect whether the linux or bsd version is running. On the OSX/BSD version the `sed --version` command fails, but on the gnu version it succeeds. 
This allows the script to work in two cases where it otherwise fails-
1. For people (like me) who install the updated gnu versions of everything on their OSX machines.
2. On other BSD style systems.
=> portable sed commands

README.md, gh-md-toc, tests/tests.bats
The feature requested by #114 is very useful for transmitting a project to another maintainer. Here I tried to change the 'added by' comment to an HTML comment. Added it to the insert mode and changed it in the tests and README too
=> Fix for #114

gh-md-toc
Rationale: indentation of sub-levels in bullet lists is 2 spaces according to github documentation, 4 spaces is very common though, 3 is less common. All are accepted by GitHub but other tools are not that flexible, typically mkdocs. 
I propose to make the size of the indentation customizable, with a default at 3 to be backward compatible. The extra parameter is `--indent`.
Thank you for considering this addition and to comment on the naming of the parameter and the actual implementation.
=> Customizable indent size

README.md
Hi, 
this PR enhances the [example](https://github.com/ekalinin/github-markdown-toc#toc-generation-with-github-actions) for use of this project with Github Actions. The problems I faced when I copy and pasted the example into my Github Action are described in issue #128.
Adding the `--hide-footer` flag makes sure that no unnecessary auto-commit is generated by the Gitub Action. For example, if you were to change the content of `foo.md`, but would leave the  structure of its headlines intact, there is no need to generate a new TOC. `gh-md-toc` adds a `footer` comment to your TOC that reads something like ``. This changes every time `gh-md-toc` is executed at a different `datetime`. Hiding the footer makes running `gh-md-toc` idempotent, if the headers in `foo.md` do not change. This …
=> Fix for  #128: Documentation enhancement for Github Actions

gh-md-toc, tests/tests.bats
This PR is trying to resolve #125. In case the end marker  is present all lines before this marker are removed for further processing.
=> Skip headers if end marker is present

gh-md-toc
Fix [#131](https://github.com/ekalinin/github-markdown-toc/issues/131).
Because `--indent` is followed by `<NUM>`, we need `shift 2` to remove two arguments when parsing it.
=> Fix #131: --indent argument makes the script crashed

gh-md-toc
Github must have changed something on their end, the HTML seems to have changed a little.
Possibly fixes https://github.com/ekalinin/github-markdown-toc/issues/143
=> Fix parsing of HTML returned from raw API

.gitignore
When writing #154 I had to add my GitHub PAT to the repo in `token.txt` to avoid rate limitations when querying the GitHub API. `token.txt` is currently not ignored in version control, which can easily lead to leaked access tokens. To avoid this, `token.txt` should by added to `.gitignore`, which I have done in this PR. I did not write an extra issue for such a small change, hope that is okay.
=> Don't leak GH token in `token.txt` by adding it to `.gitignore`
